repo_name: gl-inet/docs4.x
repo_url: https://github.com/gl-inet/docs4.x
edit_uri: ""

site_name: GL.iNet ルータードキュメント 4
site_description: GL.iNet ルーター製品向けドキュメント
site_author: GL.iNet
site_url: https://docs.gl-inet.com/router/jp/4/
site_dir: site
copyright: Copyright &copy; 2026 GL Technologies & Microuter Technologies

theme:
  name: material
  language: ja
  logo: https://static.gl-inet.com/docs/router/common/logo_white.svg
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  favicon: https://static.gl-inet.com/docs/router/common/favicon.png

plugins:
  - search
  - redirects:
      redirect_maps:
        "faq/block_no_vpn_traffic.md": "faq/block_non_vpn_traffic.md"
        "faq/i_replaced_my_old_router_with_gl_inet_router_but_no_internet.md": "faq/no_internet_after_replacing_the_old_router_with_glinet.md"
        "tutorials/how_to_connect_glinet_router_to_an_eap_network_with_advanced_settings.md": "tutorials/eap.md"
        "interface_guide/network_port_management.md": "interface_guide/ethernet_port.md"
        "tutorials/vpn_cascading.md": "tutorials/how_to_use_vpn_cascading_on_glinet_routers.md"
        "tutorials/how_to_set_up_esim.md": "tutorials/how_to_use_esim_physical_card_with_glinet_routers.md"
        "tutorials/tap_s2s_vs_tun.md": "tutorials/how_to_enable_openvpn_tap_s2s_mode_on_glinet_routers.md"
        "tutorials/build_your_own_openvpn_home_server_with_two_glrouter.md": "tutorials/build_your_own_wireguard_home_server_with_two_glinet_routers.md"
        "tutorials/can_i_use_multiwan_wired_input.md": "tutorials/configure_dual_ethernet_wan.md"
        "interface_guide/firmware_upgrade.md": "interface_guide/upgrade.md"
        "faq/i_must_use_ethernet_wan_when_use_vpn.md": "faq/do_i_have_to_configure_ethernet_wan_when_using_vpn.md"
        "faq/gl-ax1800_upgrade_to_4.md": "faq/upgrade_to_4.md"
        "faq/gl-x3000_gl-xe3000_connection_optimization.md": "faq/cellular_network_troubleshooting_guide.md"
        "faq/where_to_download_firmware.md": "faq/how_to_download_firmware.md"
        "faq/can_i_add_brume2_into_app.md": "faq/how_to_add_brume2_into_app.md"
        "tutorials/how_to_use_simpoyo_esim_physical_card_with_glinet_routers.md": "tutorials/how_to_use_esim_physical_card_with_glinet_routers.md"
        "tutorials/how_to_use_the_simpoyo_esim_physical_card_with_android_devices.md": "tutorials/how_to_use_the_esim_physical_card_with_android_devices.md"
        "tutorials/how_to_access_server_lan_device_via_domain_name.md": "tutorials/how_to_access_wgserver_lan_via_domain_name.md"
        "interface_guide/dpi_license.md": "interface_guide/dpi_engine.md"
        "tutorials/how_to_change_x3000_and_xe3000_antennas.md": "tutorials/how_to_install_or_change_antennas.md"
        "faq/amnezia_obfuscation_parameters.md": "faq/amneziawg_obfuscation_parameters.md"
        "tutorials/how_to_use_simpoyo_ufi.md": "user_guide/simpoyo-4g-ufi/index.md"

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike
  alternate:
    - name: English
      link: /router/en/4/
      lang: en
    - name: Deutsch
      link: /router/de/4/
      lang: de
    - name: Español
      link: /router/es/4/
      lang: es
    - name: Français
      link: /router/fr/4/
      lang: fr
    - name: Italiano
      link: /router/it/4/
      lang: it
    - name: 日本語
      link: /router/jp/4/
      lang: ja
    - name: Polski
      link: /router/pl/4/
      lang: pl

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.umd.js
  - javascripts/analytics.js
  - https://www.gl-inet.com/js/cookieconsent.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - admonition

nav:
  - ホーム: index.md
  - ユーザーガイド:
      - 概要: user_guide/index.md
      - GL-BE10000 (Slate 7 Pro): user_guide/gl-be10000/index.md
      - GL-MT3600BE (Beryl 7): user_guide/gl-mt3600be/index.md
      - GL-E5800 (Mudi 7): user_guide/gl-e5800/index.md
      - GL-MT5000 (Brume 3): user_guide/gl-mt5000/index.md
      - GL-BE9300 (Flint 3): user_guide/gl-be9300/index.md
      - GL-BE6500 (Flint 3e): user_guide/gl-be6500/index.md
      - GL-BE3600 (Slate 7): user_guide/gl-be3600/index.md
      - GL-X2000 (Spitz Plus): user_guide/gl-x2000/index.md
      - GL-B3000 (Marble): user_guide/gl-b3000/index.md
      - GL-MT6000 (Flint 2): user_guide/gl-mt6000/index.md
      - GL-XE3000 (Puli AX): user_guide/gl-xe3000/index.md
      - GL-X3000 (Spitz AX): user_guide/gl-x3000/index.md
      - GL-MT3000 (Beryl AX): user_guide/gl-mt3000/index.md
      - GL-AXT1800 (Slate AX): user_guide/gl-axt1800/index.md
      - GL-A1300 (Slate Plus): user_guide/gl-a1300/index.md
      - GL-AX1800 (Flint): user_guide/gl-ax1800/index.md
      - GL-MT2500/GL-MT2500A (Brume 2): user_guide/gl-mt2500/index.md
      - GL-SFT1200 (Opal): user_guide/gl-sft1200/index.md
      - GL-MT300N-V2 (Mango): user_guide/gl-mt300n-v2/index.md
      - GL-AR300M (Shadow): user_guide/gl-ar300m/index.md
      - GL-M2: user_guide/gl-m2/index.md
      - GL-S200: user_guide/gl-s200/index.md
      - GL-S20: user_guide/gl-s20/index.md
      - GL-S10: user_guide/gl-s10/index.md
      - GL-MT1300 (Beryl): user_guide/gl-mt1300/index.md
      - GL-AP1300 (Cirrus): user_guide/gl-ap1300/index.md
      - GL-E750/GL-E750V2 (Mudi/Mudi V2): user_guide/gl-e750/index.md
      - GL-X750 (Spitz): user_guide/gl-x750/index.md
      - GL-XE300 (Puli): user_guide/gl-xe300/index.md
      - GL-X300B (Collie): user_guide/gl-x300b/index.md
      - GL-AR750S (Slate): user_guide/gl-ar750s/index.md
      - GL-AR750 (Creta): user_guide/gl-ar750/index.md
      - GL-B1300 (Convexa-B): user_guide/gl-b1300/index.md
      - GL-S1300 (Convexa-S): user_guide/gl-s1300/index.md
      - GL-MV1000 (Brume): user_guide/gl-mv1000/index.md
  - FAQ:
      - 概要: faq/index.md
      - インターネット:
          - 初回セットアップ: faq/first_time_setup.md
          - ブラウザの警告について: faq/warning_from_your_browser_during_setup.md
          - キャプティブポータルでホットスポットに接続する: faq/connect_to_a_hotspot_with_captive_portal.md
          - 有線接続を作成する: faq/produce_a_wired_connection.md
      - 問題通知:
          - GL-MT2500/GL-X3000/GL-XE3000 の問題通知: faq/problem_notification_for_mt2500_x3000_xe3000.md
          - GL-X3000/GL-X2000 と EE SIM カードの問題通知と解決策: faq/problem_notification_and_solutions_for_x3000_x2000_failure_to_work_with_ee_sim_cards.md
      - トラブルシューティング:
          - ウェブ管理パネルにアクセスできません: faq/cannot_access_web_admin_panel.md
          - Android 5G ホットスポットのスキャンができない: faq/cannot_scan_android_5g_hotspot.md
          - iPhone 5G ホットスポットのスキャンができない: faq/cannot_scan_iphone_5g_hotspot.md
          - iPhone テザリング失敗: faq/iphone_tethering_fail.md
          - セルラーネットワークのトラブルシューティングガイド: faq/cellular_network_troubleshooting_guide.md
          - eSIMプロファイルのインストールに失敗する: faq/esim_profile_installation_failed.md
          - 古いルーターを GL.iNet に置き換えた後にインターネットがない: faq/no_internet_after_replacing_the_old_router_with_glinet.md
          - USB モデムが正常に動作しない: faq/usb_modem_is_not_working_properly_on_gl_inet_router.md
          - 修復またはリセット: faq/repair_network_or_reset_firmware.md
          - ルーターが文鎮化した場合の対処法: faq/debrick.md
          - MacOSはSambaに書き込めない: faq/macos_cannot_write_samba.md
          - WireGuard サーバーが正常に動作しない: faq/my_wireguard_server_is_not_working.md
          - ファームウェア更新中に「インストール中」で止まる: faq/stuck_on_installing_during_firmware_update.md
          - ファームウェアリセット中に「元に戻しています」で止まる: faq/stuck_on_reverting_during_firmware_reset.md
          - 再起動中に「再起動中」で止まる: faq/stuck_on_rebooting_during_firmware_reboot.md
          - サブネット競合の解決方法: faq/how_to_resolve_a_subnet_conflict.md
          - DDNS テストのメッセージについて: faq/why_do_I_get_a_message_from_ddns_test.md
          - VPN 速度が遅い理由: faq/why_is_my_vpn_speed_slow.md
          - ルーターのデバイス容量について: faq/what_is_the_device_capacity_of_my_router.md
          - ルーターの無線カバレッジについて: faq/what_is_the_wireless_coverage_of_my_router.md
          - Uboot バージョンのアップグレード: faq/upgrade_uboot_version.md
      - VPN:
          - OpenVPN の設定方法: interface_guide/openvpn_client.md
          - WireGuard の設定方法: interface_guide/wireguard_client.md
          - VPN 以外のトラフィックをブロックする: faq/block_non_vpn_traffic.md
          - VPN キルスイッチ: faq/block_non_vpn_traffic.md
          - TCP または UDP: faq/openvpn_tcp_udp.md
          - AmneziaWG難読化パラメーター: faq/amneziawg_obfuscation_parameters.md
          - VPN 使用時に Ethernet WAN の設定が必要か: faq/do_i_have_to_configure_ethernet_wan_when_using_vpn.md
      - アップグレード:
          - ファームウェアをダウンロード: faq/how_to_download_firmware.md
          - 手動でアップグレードまたはダウングレード: tutorials/how_to_upgrade_downgrade_router.md
      - その他:
          - LED インジケーターの状態: faq/led.md
          - GL.iNet モバイルアプリ: faq/mobile_app.md
          - Brume 2 をモバイルアプリに追加する: faq/how_to_add_brume2_into_app.md
          - WAN を LAN に変更: faq/change_wan_to_lan.md
          - HTTPS で GL.iNet と AdGuard Home にアクセス: faq/use_https_for_adh.md
          - Starlink への接続: faq/connect_glinetrouter_to_starlink.md
          - リモート Web 管理: faq/remote_access_web_admin_panel.md
          - ルーターへのリモート SSH: faq/remote_ssh_to_router.md
          - パブリック IP 確認: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
          - Opal で Wi-Fi 通話を機能させる方法: faq/how_to_make_wifi_calling_work_on_opal.md
          - すべての MAC アドレスを確認する: faq/how_can_i_know_the_lan_wifi_mac.md
          - デバイス情報を確認する: faq/where_to_find_the_device_id_mac_sn.md
          - LuCI とは: faq/what_is_luci.md
  - チュートリアル:
      - 概要: tutorials/index.md
      - VPN:
          - OpenVPN クライアントの設定: tutorials/how_to_set_up_openvpn_client.md
          - OpenVPN サーバーの設定: tutorials/how_to_set_up_openvpn_server.md
          - 2台のGL.iNetルーターで独自のWireGuardホームサーバーを構築: tutorials/build_your_own_wireguard_home_server_with_two_glinet_routers.md
          - VPN 難読化の設定: tutorials/vpn_obfuscation.md
          - NordVPN に Dedicated IP で接続する: tutorials/how_to_connect_to_nordvpn_with_dedicated_ip_on_glinet_routers.md
          - Surfshark に Dedicated IP で接続する: tutorials/how_to_connect_to_surfshark_with_dedicated_ip_on_glinet_routers.md
          - Astrorelay 経由で OpenVPN サーバーを設定する: tutorials/how_to_set_up_openvpn_server_via_astrorelay.md
          - Astrorelay 経由で WireGuard サーバーを設定する: tutorials/how_to_set_up_wireguard_server_via_astrorelay.md
          - サーバーから OpenVPN クライアント LAN にアクセスする: tutorials/openvpn_server_access_client_lan_side.md
          - サーバーから WireGuard クライアント LAN にアクセスする: tutorials/wireguard_server_access_to_client_lan_side.md
          - ドメイン名で OpenVPN サーバー LAN にアクセスする: tutorials/how_to_access_ovpnserver_lan_via_domain_name.md
          - ドメイン名で WireGuard サーバー LAN にアクセスする: tutorials/how_to_access_wgserver_lan_via_domain_name.md
          - OpenVPN TAP-S2S を有効にする: tutorials/how_to_enable_openvpn_tap_s2s_mode_on_glinet_routers.md
          - VPN カスケードを有効にする: tutorials/how_to_use_vpn_cascading_on_glinet_routers.md
          - WireGuard で外部ネットワークからの RDP を保護する: tutorials/use_wireguard_to_secure_rdp_from_outside_network.md
          - WireGuard サービスプロバイダーから設定ファイルを取得する: tutorials/how_to_get_configuration_files_from_wireguard_service_providers.md
          - OpenVPN クライアントに固定 IP を予約する: tutorials/reserve_fixed_IP_for_ovpn_client.md
          - VPN クライアント有効時に WAN アクセスを許可する: tutorials/how_to_allow_access_to_wan_when_vpn_client_enabled.md
          - VPN クライアント DNS をサーバー上流 DNS にルーティングする: tutorials/route_vpn_client_dns_to_server_upstream_dns.md
          - OpenVPN サーバー証明書を更新する: tutorials/how_to_update_openvpn_server_certificates.md
      - セルラー:
          - SMS 転送: tutorials/sms_forwarding.md
          - モジュールログを取得する: tutorials/get_module_logs.md
          - Quectel モジュールのアップグレード: tutorials/upgrade_quectel_module_software.md
          - キャリアアグリゲーションの確認方法: tutorials/how_to_check_carrier_aggregation.md
          - RV 用 Spitz AX の設定方法: tutorials/how_to_set_up_and_use_spitz_ax_gl-x3000_in_your_recreational_vehicle.md
          - 外部アンテナの取り付けまたは交換方法: tutorials/how_to_install_or_change_antennas.md
      - eSIM:
          - GL.iNet ルーターで eSIM 物理カードを使用する: tutorials/how_to_use_esim_physical_card_with_glinet_routers.md
          - Android デバイスで eSIM 物理カードを使用する: tutorials/how_to_use_the_esim_physical_card_with_android_devices.md
          - SIMPoYo uFi の使い方: tutorials/how_to_use_simpoyo_ufi.md
      - GoodCloud:
          - Site to Site: tutorials/goodcloud_site_to_site.md
          - GoodCloud 経由で LuCI にアクセスする: tutorials/how_to_access_the_luci_interface_via_goodcloud.md
      - ネットワーク:
          - EAP ネットワークへの接続: tutorials/eap.md
          - ゲストネットワークの設定方法: tutorials/how_to_set_up_a_guest_network.md
          - ドロップインゲートウェイの設定方法: tutorials/how_to_set_up_drop_in_gateway.md
          - プライマリルーターでポート転送を設定する方法: tutorials/how_to_set_up_port_forwarding.md
          - デュアル有線 WAN アクセスの設定: tutorials/configure_dual_ethernet_wan.md
      - その他:
          - クライアントデバイスをブロックする方法: tutorials/how_to_block_client_devices.md
          - クライアントデバイスに静的 IP を手動で設定する: tutorials/manually_configure_static_ip.md
          - パブリック IP を持っているかどうかを確認する: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
          - ルーターをアップグレードまたはダウングレードする方法: tutorials/how_to_upgrade_downgrade_router.md
          - SSH でルーターにログインする: tutorials/ssh_log_in_to_the_router.md
          - WinSCP を使用して共有ファイルにアクセスする: tutorials/winscp_share_file.md
          - WinSCP を使用してファイルを変更する: tutorials/how_to_use_winscp_to_modify_files_on_glinet_routers.md
          - T-Mobile SIM カードを有効化またはチャージする: tutorials/how_to_activate_top_up_sim_cards.md
          - ゲーミング NAT タイプを変更する: tutorials/how_to_change_the_nat_type_on_gaming.md
          - モバイルアプリのログを取得する: tutorials/how_to_retrieve_the_mobile_app_log.md
          - VPN ドメインおよび IP フィルタリングルールの設定: tutorials/how_to_configure_domain_and_ip_filtering_rules_for_glinet_routers_via_an_online_text_file.md
          - GoodCloud 経由でテクニカルサポートを受ける: tutorials/technical_support_via_goodcloud.md
  - インターフェースガイド:
      - 概要: interface_guide/index.md
      - インターネット接続:
          - インターネット: interface_guide/internet.md
          - イーサネット: interface_guide/internet_ethernet.md
          - リピータ: interface_guide/internet_repeater.md
          - テザリング: interface_guide/internet_tethering.md
          - セルラー: interface_guide/internet_cellular.md
          - SMS: interface_guide/sms.md
          - デュアルイーサネット WAN: interface_guide/dual-ethernet_wan.md
      - ワイヤレス:
          - ワイヤレス: interface_guide/wireless.md
      - クライアント:
          - クライアント: interface_guide/clients.md
      - クラウドサービス:
          - GoodCloud: interface_guide/cloud.md
          - AstroWarp: interface_guide/astrowarp.md
      - VPN:
          - VPN ダッシュボード (v4.7): interface_guide/vpn_dashboard_v4.7.md
          - VPN ダッシュボード (v4.8): interface_guide/vpn_dashboard_v4.8.md
          - VPN ダッシュボード (v4.9): interface_guide/vpn_dashboard_v4.9.md
          - OpenVPN クライアント: interface_guide/openvpn_client.md
          - OpenVPN サーバー: interface_guide/openvpn_server.md
          - WireGuard クライアント: interface_guide/wireguard_client.md
          - WireGuard サーバー: interface_guide/wireguard_server.md
          - Tor: interface_guide/tor.md
      - アプリケーション:
          - プラグイン: interface_guide/plugins.md
          - ダイナミック DNS: interface_guide/ddns.md
          - ネットワークストレージ: interface_guide/network_storage.md
          - AdGuard Home: interface_guide/adguardhome.md
          - ペアレンタルコントロール: interface_guide/parental_control.md
          - ZeroTier: interface_guide/zerotier.md
          - Tailscale: interface_guide/tailscale.md
          - eSIM 管理: interface_guide/esim_management.md
      - ネットワーク:
          - ファイアウォール: interface_guide/firewall.md
          - ポート転送: interface_guide/port_forwarding.md
          - マルチ WAN: interface_guide/multi-wan.md
          - LAN: interface_guide/lan.md
          - ゲストネットワーク: interface_guide/guest_network.md
          - DNS: interface_guide/dns.md
          - Ethernet ポート: interface_guide/ethernet_port.md
          - ネットワークモード: interface_guide/network_mode.md
          - IPv6: interface_guide/ipv6.md
          - MAC アドレス: interface_guide/mac_address.md
          - ドロップインゲートウェイ: interface_guide/drop-in_gateway.md
          - IGMP スヌーピング: interface_guide/igmp_snooping.md
          - ハードウェアアクセラレーション: interface_guide/hardware_acceleration.md
          - ネットワークアクセラレーション: interface_guide/network_acceleration.md
          - NAT 設定: interface_guide/nat_settings.md
      - フロー制御:
          - DPI ライセンス: interface_guide/dpi_engine.md
          - データ統計: interface_guide/data_statistics.md
          - コンテンツフィルター: interface_guide/content_filter.md
          - QoS: interface_guide/qos.md
          - SQM: interface_guide/sqm.md
      - システム:
          - 概要: interface_guide/system_overview.md
          - アップグレード: interface_guide/upgrade.md
          - スケジュールされたタスク: interface_guide/scheduled_tasks.md
          - 管理者パスワード: interface_guide/admin_password.md
          - ディスプレイ管理: interface_guide/display_management.md
          - USB & 電源: interface_guide/usb_power.md
          - タイムゾーン: interface_guide/time_zone.md
          - トグルボタン設定: interface_guide/toggle_button_settings.md
          - ログ: interface_guide/log.md
          - セキュリティ: interface_guide/security.md
          - ファームウェアのリセット: interface_guide/reset_firmware.md
          - 詳細設定: interface_guide/advanced_settings.md
          - 言語: interface_guide/ui_languages.md
          - ヘルプ: interface_guide/help.md
  - ビデオライブラリ:
      - 概要: video_library/index.md
      - 新製品をご紹介します: video_library/products.md
      - 開梱と初回セットアップ: video_library/unboxing_first_set_up.md
      - チュートリアル: video_library/tutorials.md
  - コミュニティ:
      - 概要: community/index.md
