repo_name: gl-inet/docs4.x
repo_url: https://github.com/gl-inet/docs4.x
edit_uri: ""

site_name: GL.iNet Router-Dokumentation 4
site_description: Dokumentation für GL.iNet-Routerprodukte
site_author: GL.iNet
site_url: https://docs.gl-inet.com/router/de/4/
site_dir: site
copyright: Copyright &copy; 2026 GL Technologies & Microuter Technologies

theme: 
  name: material
  language: de
  logo: https://static.gl-inet.com/docs/router/common/logo_white.svg
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  favicon: https://static.gl-inet.com/docs/router/common/favicon.png

plugins:
  - search
  - redirects:
      redirect_maps:
        'tutorials/vpn_cascading.md': 'tutorials/how_to_use_vpn_cascading_on_glinet_routers.md'
        'tutorials/how_to_set_up_esim.md': 'tutorials/how_to_use_esim_physical_card_with_glinet_routers.md'
        'tutorials/tap_s2s_vs_tun.md': 'tutorials/how_to_enable_openvpn_tap_s2s_mode_on_glinet_routers.md'
        'tutorials/vpn_cascading.md': 'tutorials/how_to_use_vpn_cascading_on_glinet_routers.md'
        'tutorials/build_your_own_openvpn_home_server_with_two_glrouter.md': 'tutorials/build_your_own_wireguard_home_server_with_two_glinet_routers.md'
        'tutorials/can_i_use_multiwan_wired_input.md': 'tutorials/configure_dual_ethernet_wan.md'
        'interface_guide/firmware_upgrade.md': 'interface_guide/upgrade.md'
        'faq/i_must_use_ethernet_wan_when_use_vpn.md': 'faq/do_i_have_to_configure_ethernet_wan_when_using_vpn.md'
        'faq/gl-ax1800_upgrade_to_4.md': 'faq/upgrade_to_4.md'
        'faq/gl-x3000_gl-xe3000_connection_optimization.md': 'faq/cellular_network_troubleshooting_guide.md'
        'faq/where_to_download_firmware.md': 'faq/how_to_download_firmware.md'
        'faq/can_i_add_brume2_into_app.md': 'faq/how_to_add_brume2_into_app.md'
        'faq/i_replaced_my_old_router_with_gl_inet_router_but_no_internet.md': 'faq/no_internet_after_replacing_the_old_router_with_glinet.md'
        'tutorials/how_to_use_simpoyo_esim_physical_card_with_glinet_routers.md': 'tutorials/how_to_use_esim_physical_card_with_glinet_routers.md'
        'tutorials/how_to_use_the_simpoyo_esim_physical_card_with_android_devices.md': 'tutorials/how_to_use_the_esim_physical_card_with_android_devices.md'
        'tutorials/how_to_access_server_lan_device_via_domain_name.md': 'tutorials/how_to_access_wgserver_lan_via_domain_name.md'
        'tutorials/how_to_connect_glinet_router_to_an_eap_network_with_advanced_settings.md': 'tutorials/eap.md'
        'interface_guide/network_port_management.md': 'interface_guide/ethernet_port.md'
        'interface_guide/dpi_license.md': 'interface_guide/dpi_engine.md'
        'tutorials/how_to_change_x3000_and_xe3000_antennas.md': 'tutorials/how_to_install_or_change_antennas.md'

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike
  alternate:
    - name: Deutsch
      link: /router/de/4/
      lang: de
    - name: English
      link: /router/en/4/
      lang: en
    - name: Español
      link: /router/es/4/
      lang: es
    - name: Français
      link: /router/fr/4/
      lang: fr
    - name: Italiano
      link: /router/it/4/
      lang: it
    - name: 日本語
      link: /router/jp/4/
      lang: ja
    - name: Polski
      link: /router/pl/4/
      lang: pl

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.css

  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.umd.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/analytics.js
  - javascripts/extra.js
  - javascripts/cookieconsent.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - admonition

nav:
  - Startseite: index.md
  - Benutzerhandbuch:
    - Übersicht: user_guide/index.md
    - GL-MT3600BE (Beryl 7): user_guide/gl-mt3600be/index.md
    - GL-E5800 (Mudi 7): user_guide/gl-e5800/index.md
    - GL-MT5000 (Brume 3): user_guide/gl-mt5000/index.md
    - GL-BE9300 (Flint 3): user_guide/gl-be9300/index.md
    - GL-BE6500 (Flint 3e): user_guide/gl-be6500/index.md
    - GL-BE3600 (Slate 7): user_guide/gl-be3600/index.md
    - GL-X2000 (Spitz Plus): user_guide/gl-x2000/index.md
    - GL-B3000 (Marble): user_guide/gl-b3000/index.md
    - GL-MT6000 (Flint 2): user_guide/gl-mt6000/index.md
    - GL-XE3000 (Puli AX): user_guide/gl-xe3000/index.md
    - GL-X3000 (Spitz AX): user_guide/gl-x3000/index.md
    - GL-MT3000 (Beryl AX): user_guide/gl-mt3000/index.md
    - GL-AXT1800 (Slate AX): user_guide/gl-axt1800/index.md
    - GL-A1300 (Slate Plus): user_guide/gl-a1300/index.md
    - GL-AX1800 (Flint): user_guide/gl-ax1800/index.md
    - GL-MT2500/GL-MT2500A (Brume 2): user_guide/gl-mt2500/index.md
    - GL-SFT1200 (Opal): user_guide/gl-sft1200/index.md
    - GL-MT300N-V2 (Mango): user_guide/gl-mt300n-v2/index.md
    - GL-AR300M (Shadow): user_guide/gl-ar300m/index.md
    - GL-M2: user_guide/gl-m2/index.md
    - GL-S200: user_guide/gl-s200/index.md
    - GL-S20: user_guide/gl-s20/index.md
    - GL-S10: user_guide/gl-s10/index.md
    - GL-MT1300 (Beryl): user_guide/gl-mt1300/index.md
    - GL-AP1300 (Cirrus): user_guide/gl-ap1300/index.md
    - GL-E750/GL-E750V2 (Mudi/Mudi V2): user_guide/gl-e750/index.md
    - GL-X750 (Spitz): user_guide/gl-x750/index.md
    - GL-XE300 (Puli): user_guide/gl-xe300/index.md
    - GL-X300B (Collie): user_guide/gl-x300b/index.md
    - GL-AR750S (Slate): user_guide/gl-ar750s/index.md
    - GL-AR750 (Creta): user_guide/gl-ar750/index.md
    - GL-B1300 (Convexa-B): user_guide/gl-b1300/index.md
    - GL-S1300 (Convexa-S): user_guide/gl-s1300/index.md
    - GL-MV1000 (Brume): user_guide/gl-mv1000/index.md
  - FAQ:
    - Übersicht: faq/index.md
    - Internet:
      - Ersteinrichtung: faq/first_time_setup.md
      - Warnung des Browsers: faq/warning_from_your_browser_during_setup.md
      - Verbindung mit öffentlichem Hotspot mit Captive Portal: faq/connect_to_a_hotspot_with_captive_portal.md
      - Ethernet-Gerät nur über Wi-Fi verbinden: faq/produce_a_wired_connection.md
    - Problemhinweise:
      - Problemhinweis für GL-MT2500/GL-X3000/GL-XE3000: faq/problem_notification_for_mt2500_x3000_xe3000.md
      - Problemhinweis und Lösungen für GL-X3000/GL-X2000 bei Problemen mit EE-SIM-Karten: faq/problem_notification_and_solutions_for_x3000_x2000_failure_to_work_with_ee_sim_cards.md
    - Fehlerbehebung:
      - Kein Zugriff auf das webbasierte Admin Panel: faq/cannot_access_web_admin_panel.md
      - Android-5G-Hotspot kann nicht gescannt werden: faq/cannot_scan_android_5g_hotspot.md
      - iPhone-5G-Hotspot kann nicht gescannt werden: faq/cannot_scan_iphone_5g_hotspot.md
      - iPhone-Tethering fehlgeschlagen: faq/iphone_tethering_fail.md
      - Leitfaden zur Fehlerbehebung bei Mobilfunknetzen: faq/cellular_network_troubleshooting_guide.md
      - Kein Internet nach dem Ersetzen des alten Routers durch einen GL.iNet-Router: faq/no_internet_after_replacing_the_old_router_with_glinet.md
      - USB-Modem funktioniert nicht: faq/usb_modem_is_not_working_properly_on_gl_inet_router.md
      - Netzwerk reparieren oder zurücksetzen: faq/repair_network_or_reset_firmware.md
      - Was tun, wenn der Router beschädigt ist?: faq/debrick.md
      - macOS kann nicht auf eine Samba-Freigabe schreiben: faq/macos_cannot_write_samba.md
      - WireGuard-Server funktioniert nicht ordnungsgemäß: faq/my_wireguard_server_is_not_working.md
      - Hängt bei „Installing“ während des Firmware-Updates: faq/stuck_on_installing_during_firmware_update.md
      - Hängt bei „Reverting“ während des Firmware-Resets: faq/stuck_on_reverting_during_firmware_reset.md
      - Hängt bei „Rebooting“ während des Firmware-Neustarts: faq/stuck_on_rebooting_during_firmware_reboot.md
      - Wie behebt man einen Subnetzkonflikt?: faq/how_to_resolve_a_subnet_conflict.md
      - Warum erscheint eine Meldung beim DDNS-Test?: faq/why_do_I_get_a_message_from_ddns_test.md
      - Warum ist meine VPN-Geschwindigkeit langsamer als erwartet?: faq/why_is_my_vpn_speed_slow.md
      - Wie hoch ist die Gerätekapazität meines Routers?: faq/what_is_the_device_capacity_of_my_router.md
      - Wie groß ist die WLAN-Abdeckung meines Routers?: faq/what_is_the_wireless_coverage_of_my_router.md
      - U-Boot-Version aktualisieren: faq/upgrade_uboot_version.md
    - VPN:
      - OpenVPN einrichten: interface_guide/openvpn_client.md
      - WireGuard einrichten: interface_guide/wireguard_client.md
      - Nicht-VPN-Datenverkehr blockieren: faq/block_non_vpn_traffic.md
      - VPN Kill Switch: faq/block_non_vpn_traffic.md
      - TCP oder UDP: faq/openvpn_tcp_udp.md
      - Muss ich Ethernet WAN bei Verwendung eines VPN konfigurieren?: faq/do_i_have_to_configure_ethernet_wan_when_using_vpn.md
    - Upgrade:
      - Firmware herunterladen: faq/how_to_download_firmware.md
      - Manuell aktualisieren oder downgraden: tutorials/how_to_upgrade_downgrade_router.md
    - Weitere Themen:
      - Status der LED-Anzeige: faq/led.md
      - GL.iNet App: faq/mobile_app.md
      - Brume 2 zur mobilen App hinzufügen: faq/how_to_add_brume2_into_app.md
      - WAN in LAN ändern: faq/change_wan_to_lan.md
      - Zugriff auf GL.iNet und AdGuard Home über HTTPS: faq/use_https_for_adh.md
      - Verbindung mit Starlink Dish: faq/connect_glinetrouter_to_starlink.md
      - Remote Web Admin: faq/remote_access_web_admin_panel.md
      - Remote-SSH zum Router: faq/remote_ssh_to_router.md
      - Öffentliche IP prüfen: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
      - Wi-Fi Calling auf Opal zum Laufen bringen: faq/how_to_make_wifi_calling_work_on_opal.md
      - Alle MAC-Adressen finden: faq/how_can_i_know_the_lan_wifi_mac.md
      - Geräteinformationen finden: faq/where_to_find_the_device_id_mac_sn.md
      - Was ist LuCI?: faq/what_is_luci.md
  - Tutorials:
    - Übersicht: tutorials/index.md
    - VPN: 
      - OpenVPN-Client einrichten: tutorials/how_to_set_up_openvpn_client.md
      - OpenVPN-Server einrichten: tutorials/how_to_set_up_openvpn_server.md
      - Eigenen WireGuard-Heimserver aufbauen: tutorials/build_your_own_wireguard_home_server_with_two_glinet_routers.md
      - VPN-Obfuskation einrichten: tutorials/vpn_obfuscation.md
      - NordVPN mit einer dedizierten IP verbinden: tutorials/how_to_connect_to_nordvpn_with_dedicated_ip_on_glinet_routers.md
      - Surfshark mit einer dedizierten IP verbinden: tutorials/how_to_connect_to_surfshark_with_dedicated_ip_on_glinet_routers.md
      - OpenVPN-Server über AstroRelay einrichten: tutorials/how_to_set_up_openvpn_server_via_astrorelay.md
      - WireGuard-Server über AstroRelay einrichten: tutorials/how_to_set_up_wireguard_server_via_astrorelay.md
      - Auf das OpenVPN-Client-LAN vom Server aus zugreifen: tutorials/openvpn_server_access_client_lan_side.md
      - Auf das WireGuard-Client-LAN vom Server aus zugreifen: tutorials/wireguard_server_access_to_client_lan_side.md
      - Auf das OpenVPN-Server-LAN vom Client per Domainnamen zugreifen: tutorials/how_to_access_ovpnserver_lan_via_domain_name.md
      - Auf das WireGuard-Server-LAN vom Client per Domainnamen zugreifen: tutorials/how_to_access_wgserver_lan_via_domain_name.md
      - OpenVPN TAP-S2S aktivieren: tutorials/how_to_enable_openvpn_tap_s2s_mode_on_glinet_routers.md
      - VPN-Cascading aktivieren: tutorials/how_to_use_vpn_cascading_on_glinet_routers.md
      - WireGuard zum Schutz von RDP von außerhalb des Netzwerks verwenden: tutorials/use_wireguard_to_secure_rdp_from_outside_network.md
      - Konfigurationsdateien von WireGuard-Dienstanbietern abrufen: tutorials/how_to_get_configuration_files_from_wireguard_service_providers.md
      - Feste IP für OpenVPN-Client reservieren: tutorials/reserve_fixed_IP_for_ovpn_client.md
      - Zugriff auf WAN erlauben, wenn VPN-Client aktiviert ist: tutorials/how_to_allow_access_to_wan_when_vpn_client_enabled.md
      - DNS des VPN-Clients zum Upstream-DNS des Servers leiten: tutorials/route_vpn_client_dns_to_server_upstream_dns.md
      - OpenVPN-Server-Zertifikate aktualisieren: tutorials/how_to_update_openvpn_server_certificates.md
    - Mobilfunk:
      - SMS-Weiterleitung: tutorials/sms_forwarding.md
      - Modulprotokolle abrufen: tutorials/get_module_logs.md
      - Quectel-Modul aktualisieren: tutorials/upgrade_quectel_module_software.md
      - Status der Carrier Aggregation prüfen: tutorials/how_to_check_carrier_aggregation.md
      - Spitz AX für ein Wohnmobil einrichten: tutorials/how_to_set_up_and_use_spitz_ax_gl-x3000_in_your_recreational_vehicle.md
      - Externe Antennen installieren oder austauschen: tutorials/how_to_install_or_change_antennas.md
    - eSIM:
      - eSIM-Physikkarte mit GL.iNet-Routern verwenden: tutorials/how_to_use_esim_physical_card_with_glinet_routers.md
      - eSIM-Physikkarte mit Android-Geräten verwenden: tutorials/how_to_use_the_esim_physical_card_with_android_devices.md
      - SIMPoYo uFi verwenden: tutorials/how_to_use_simpoyo_ufi.md
    - GoodCloud:
      - Site-to-Site: tutorials/goodcloud_site_to_site.md
      - Über GoodCloud auf LuCI zugreifen: tutorials/how_to_access_the_luci_interface_via_goodcloud.md
    - Network:
      - Verbindung mit EAP-Netzwerk: tutorials/eap.md
      - Gastnetzwerk einrichten: tutorials/how_to_set_up_a_guest_network.md
      - Drop-in Gateway einrichten: tutorials/how_to_set_up_drop_in_gateway.md
      - Portweiterleitung auf dem Hauptrouter einrichten: tutorials/how_to_set_up_port_forwarding.md
      - Dualen kabelgebundenen WAN-Zugang konfigurieren: tutorials/configure_dual_ethernet_wan.md
    - Weitere Themen:
      - Client-Geräte blockieren: tutorials/how_to_block_client_devices.md
      - Statische IP auf Client-Geräten manuell konfigurieren: tutorials/manually_configure_static_ip.md
      - Prüfen, ob eine öffentliche IP vorhanden ist: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
      - Router aktualisieren oder downgraden: tutorials/how_to_upgrade_downgrade_router.md
      - Per SSH am Router anmelden: tutorials/ssh_log_in_to_the_router.md
      - Mit WinSCP auf Freigabedateien zugreifen: tutorials/winscp_share_file.md
      - Mit WinSCP Dateien ändern: tutorials/how_to_use_winscp_to_modify_files_on_glinet_routers.md
      - T-Mobile-SIM-Karten aktivieren oder aufladen: tutorials/how_to_activate_top_up_sim_cards.md
      - NAT-Typ beim Gaming ändern: tutorials/how_to_change_the_nat_type_on_gaming.md
      - Protokoll der mobilen App abrufen: tutorials/how_to_retrieve_the_mobile_app_log.md
      - Domain- und IP-Filterregeln für VPN konfigurieren: tutorials/how_to_configure_domain_and_ip_filtering_rules_for_glinet_routers_via_an_online_text_file.md
      - Technischer Support über GoodCloud: tutorials/technical_support_via_goodcloud.md
  - Oberflächenleitfaden:
    - Übersicht: interface_guide/index.md
    - Internetverbindung:
      - Internet: interface_guide/internet.md
      - Ethernet: interface_guide/internet_ethernet.md
      - Repeater: interface_guide/internet_repeater.md
      - Tethering: interface_guide/internet_tethering.md
      - Cellular: interface_guide/internet_cellular.md
      - SMS: interface_guide/sms.md
      - Dual-Ethernet WAN: interface_guide/dual-ethernet_wan.md
    - WLAN:
      - WLAN: interface_guide/wireless.md
    - Clients:
      - Clients: interface_guide/clients.md
    - Cloud-Dienste:
      - GoodCloud: interface_guide/cloud.md
      - AstroWarp: interface_guide/astrowarp.md
    - VPN:
      - VPN Dashboard: interface_guide/vpn_dashboard.md
      - OpenVPN-Client: interface_guide/openvpn_client.md
      - OpenVPN-Server: interface_guide/openvpn_server.md
      - WireGuard-Client: interface_guide/wireguard_client.md
      - WireGuard-Server: interface_guide/wireguard_server.md
      - Tor: interface_guide/tor.md
    - Anwendungen:
      - Plug-ins: interface_guide/plugins.md
      - Dynamisches DNS: interface_guide/ddns.md
      - Netzwerkspeicher: interface_guide/network_storage.md
      - AdGuard Home: interface_guide/adguardhome.md
      - Parental Control: interface_guide/parental_control.md
      - ZeroTier: interface_guide/zerotier.md
      - Tailscale: interface_guide/tailscale.md
      - eSIM-Verwaltung: tutorials/how_to_use_esim_physical_card_with_glinet_routers.md
    - Network:
      - Firewall: interface_guide/firewall.md
      - Port Forwarding: interface_guide/port_forwarding.md
      - Multi-WAN: interface_guide/multi-wan.md
      - LAN: interface_guide/lan.md
      - Gastnetzwerk: interface_guide/guest_network.md
      - DNS: interface_guide/dns.md
      - Ethernet-Port: interface_guide/ethernet_port.md
      - Netzwerkmodus: interface_guide/network_mode.md
      - IPv6: interface_guide/ipv6.md
      - MAC-Adresse: interface_guide/mac_address.md
      - Drop-in Gateway: interface_guide/drop-in_gateway.md
      - IGMP Snooping: interface_guide/igmp_snooping.md
      - Hardwarebeschleunigung: interface_guide/hardware_acceleration.md
      - Netzwerkbeschleunigung: interface_guide/network_acceleration.md
      - NAT-Einstellungen: interface_guide/nat_settings.md
    - Verkehrssteuerung:
      - DPI-Lizenz: interface_guide/dpi_license.md
      - Datenstatistiken: interface_guide/data_statistics.md
      - Inhaltsfilter: interface_guide/content_filter.md
      - QoS: interface_guide/qos.md
      - SQM: interface_guide/sqm.md
    - System:
      - Übersicht: interface_guide/system_overview.md
      - Upgrade: interface_guide/upgrade.md
      - Geplante Aufgaben: interface_guide/scheduled_tasks.md
      - Admin-Passwort: interface_guide/admin_password.md
      - Display-Verwaltung: interface_guide/display_management.md
      - USB & Stromversorgung: interface_guide/usb_power.md
      - Zeitzone: interface_guide/time_zone.md
      - Einstellungen für Umschalttaste: interface_guide/toggle_button_settings.md
      - Protokoll: interface_guide/log.md
      - Sicherheit: interface_guide/security.md
      - Firmware zurücksetzen: interface_guide/reset_firmware.md
      - Erweiterte Einstellungen: interface_guide/advanced_settings.md
      - Sprache: interface_guide/ui_languages.md
      - Hilfe: interface_guide/help.md
  - Videobibliothek:
    - Übersicht: video_library/index.md
    - Unsere neuen Produkte kennenlernen: video_library/products.md
    - Unboxing & Ersteinrichtung: video_library/unboxing_first_set_up.md
    - Tutorials: video_library/tutorials.md
  - Community:
    - Übersicht: community/index.md
